apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-page
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xtemplate24/cooltakehomechalenge.git
    targetRevision: HEAD
    path: app-deployments/second-page-app
  destination:
    server: https://kubernetes.default.svc
    namespace: second-page-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
